### ISSUE TITLE
Support ASN and Proxy Information with IP2Location.io API

### ISSUE THREAD

**Issue by ip2location-com** [Prvvv/IPa4#1]
I would like to introduce the IP2Location.io API with IP geolocation information.

Based on your codes, you can enrich your project with ASN and proxy information using the Free plan of IP2Location.io.

**Comment by Prvvv** [comment]
Hi,

This tool already uses HTTP based get requests to retrieve information from open source online API's- ASN and Proxy server detection is already a feature in this tool so there is no need for additional libraries. 

Thanks - prv
